name: getx_pattern_starter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.4
  sp_util: 2.0.3
  imageview360: 1.3.0
  google_fonts: 3.0.1
  carousel_slider: 4.1.1
  intl: ^0.17.0
  expandable_text: 2.3.0
  flutter: 
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  material_design_icons_flutter: ^6.0.7096

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

